#!/bin/bash

python -m torch.distributed.launch --nproc_per_node=8 main_dino.py --bn True \
--arch SLaK_tiny --kernel_size 9 9 9 9 3 --epochs 100 --batch_size_per_gpu 64 \
--data_path /datadrive_c/imagenet/train --output_dir /datadrive_c/ssl/slak_9_bn_300_tiny_rep3/
