#!/bin/bash
#SBATCH --job-name=dino_slak_9_bn_rep_bs96
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=4
#SBATCH --gpus=4
#SBATCH -t 1-23:59:59
#SBATCH --exclusive
#SBATCH --cpus-per-task=18
#SBATCH -o dino_slak_9_bn_rep_bs96.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate slak

python -m torch.distributed.launch --nproc_per_node=4 main_dino.py --bn True \
--arch SLaK_tiny --kernel_size 9 9 9 9 3 --epochs 100 --batch_size_per_gpu 64 \
--data_path /datadrive_c/imagenet/train --output_dir /datadrive_c/ssl/slak_9_bn_300_tiny_rep3/


source deactivate