#!/bin/bash


nohup python -m torch.distributed.launch --nproc_per_node=8 main_dino.py --arch swin_tiny --teacher_temp 0.07 --warmup_teacher_temp_epochs 30 --norm_last_layer false  \
--data_path /datadrive_c/imagenet/train --output_dir /datadrive_c/ssl/swin_tiny_300/ \
--batch_size_per_gpu 64 --epochs 300  \
--use_dense_prediction False --cfg experiments/imagenet/swin/swin_tiny_patch4_window7_224.yaml > swin_tiny_300.txt 2>&1 &

