#!/bin/bash
#SBATCH --job-name=dino_slak_9_bn_rep
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=4
#SBATCH --gpus=4
#SBATCH -t 3-11:59:59
#SBATCH --exclusive
#SBATCH --cpus-per-task=72
#SBATCH -o dino_slak_9_bn_rep.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate LoRA

python -m torch.distributed.launch --nproc_per_node=1 main_dino.py --bn True \
--arch SLaK_tiny --kernel_size 9 9 9 9 3 --epochs 100 --batch_size_per_gpu 96 \
--data_path /projects/2/managed_datasets/imagenet/train --output_dir /projects/0/prjste21060/projects/dino/dino_slak_9_bn_rep3/


source deactivate