#!/bin/bash
#SBATCH --job-name=dino_vit_small_64
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --gpus=4
#SBATCH -t 2-23:59:59
#SBATCH --exclusive
#SBATCH --cpus-per-task=72
#SBATCH -o dino_vit_small_64.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate LoRA

python -m torch.distributed.launch --nproc_per_node=1 main_dino.py \
--arch vit_small  --epochs 100 --batch_size_per_gpu 64 \
--data_path /projects/2/managed_datasets/imagenet/train --output_dir /projects/0/prjste21060/projects/dino/dino_vit_small_64/


source deactivate