#!/bin/bash
#SBATCH --job-name=dino_slak_15_nobn
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --gpus=4
#SBATCH -t 2-11:59:59
#SBATCH --exclusive
#SBATCH --cpus-per-task=72
#SBATCH -o dino_slak_15_nobn_resume.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate LoRA

python -m torch.distributed.launch --nproc_per_node=4 main_dino.py \
--arch SLaK_tiny --kernel_size 15 15 15 15 100 --epochs 100 --bn False --batch_size_per_gpu 128 \
--data_path /projects/2/managed_datasets/imagenet/train --output_dir /projects/0/prjste21060/projects/dino/dino_slak_15_nobn/


source deactivate