#!/bin/bash
#SBATCH --job-name=dino_slak_tiny_300epochs
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --gpus=4
#SBATCH -t 2-23:59:59
#SBATCH --exclusive
#SBATCH --cpus-per-task=72
#SBATCH -o dino_slak_tiny_300epochs.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate LoRA

python -m torch.distributed.launch --nproc_per_node=1 main_dino.py \
--arch SLaK_tiny --kernel_size 7 7 7 7 100 --epochs 300 --teacher_temp 0.07 --warmup_teacher_temp_epochs 30 \
--data_path /projects/2/managed_datasets/imagenet/train --output_dir /projects/0/prjste21060/projects/dino/test


source deactivate